title: Sample for kcc-md-pricingdata-exp
summary: A pet store manager.
description: This is a sample server for a pet store.
contact:
  name: API Support
  url: https://www.example.com/support
  email: support@example.com
version: 1.0.1

